name: A workflow for my Hello World file

on:
pull_request
push:
  branches:
    -master
    -develop
       
jobs: 
  test:
    name: Running unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@
      - name: use Node.js S(( matrix.node-version ))
       uses: ./action-a
        with:
          node version: S(( matrix.node-version ))
        name: Install
        run: npm install
        name: Test
        Run: mpn test
        env:
        CI: true
      
